# Generated by Django 5.0.2 on 2024-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=122)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
